### ISSUE TITLE
Recipe App: Kanban board setup

### ISSUE THREAD

**Issue by ginabeki** [ginabeki/recipe_app#11]
### Team members:-
This project comprises two team members:-
1. @abdallahmalima 
2. @ginabeki 

### What we have done so far

- Completed setting up the [Kanban board](https://github.com/users/ginabeki/projects/3) and assigned tasks to each team member
- Set up the git-flow

**Comment by prolajumokeoni** [comment]
HI @ginabeki and @abdallahmalima, Kindly update the issue description above with the github project(kanban board)  link

**Comment by ginabeki** [comment]
Hi @prolajumokeoni , we have already updated our description with the kanban board link.

**Comment by prolajumokeoni** [comment]
Hi @ginabeki and @abdallahmalima, this is what I see when I click on the link, can you confirm  the  github project(kanban board)  is public

![Screenshot_757](https://user-images.githubusercontent.com/69638013/224673931-6abc6e44-65a3-4754-8d30-575b81c133c4.png)

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the correct link to your github project(kanban board), please update it 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Olamarx** [comment]
Hi Team, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Kanban Board ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] While you added points to others, there are some with no points, I would implore you to add it to all and make it fair in distribution.
![image](https://user-images.githubusercontent.com/86200356/224697805-1849f7c4-e2dd-4da5-82ff-c72d29ba25e7.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Reem-lab** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- Great working on set up the kanban 🤩
- Great working on adding the points 🤩

## Optional suggestions
- [ OPTIONAL ] I think it would be great if you divided the tasks between you fairly so the last task you can give it to both of you, so you can work together on it instead of just one of you! 🤩💯✨

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
